name: flake update

# Controls when the workflow will run
on:
  schedule: 
  - cron: "0 0 * * 1"
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v13
      - name: Update Nix Flake Lock
        uses: DeterminateSystems/update-flake-lock@v21
