name: Cachix-push


on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v13
      - uses: DeterminateSystems/magic-nix-cache-action@v6
      - uses: cachix/cachix-action@v15
        with:
          name: snowy-cache
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix flake check


          
